port: 8080
apiToken:
  expirationMinutes: 60
  secret: your-secret-key
interviewServer:
  baseUrl: http://interview-test-server:5000
redis:
  address: tax-bracket-cache:6379
  password: bD5%4a#9sRv7
httpClient:
  timeoutMs: 5000
  retry:
    max: 5
    wait:
      minMs: 1000
      maxMs: 5000