version: "3"

services:
  tax-calculator:
    build:
      context: .
      dockerfile: Dockerfile
      target: service
    depends_on:
      - interview-test-server
      - tax-bracket-cache
    ports:
      - 8080:8080

  integration-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: integration-test
    environment:
      - INTERVIEW_SERVER=http://interview-test-server:5000
      - TAX_CALCULATOR_SERVER=http://tax-calculator:8080
    depends_on:
      - interview-test-server
      - tax-calculator
      - tax-bracket-cache

  interview-test-server:
    image: ptsdocker16/interview-test-server
    init: true
    restart: always
    ports:
      - 5000:5000

  tax-bracket-cache:
    image: redis:7.0.11-alpine
    ports:
      - 6379:6379
    command: --requirepass bD5%4a#9sRv7