// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tax/{year}}": {
            "get": {
                "description": "calculate taxes for given a salary and tax year",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "taxes"
                ],
                "summary": "calculate taxes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tax year",
                        "name": "year",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/taxcalculator.TaxCalculation"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.taxServerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.taxServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.taxServerError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "main.taxServerResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "taxcalculator.BracketTax": {
            "type": "object",
            "properties": {
                "band": {
                    "$ref": "#/definitions/taxclient.Bracket"
                },
                "tax": {
                    "type": "string"
                }
            }
        },
        "taxcalculator.TaxCalculation": {
            "type": "object",
            "properties": {
                "effective_rate": {
                    "type": "string"
                },
                "taxes_by_band": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/taxcalculator.BracketTax"
                    }
                },
                "total_taxes": {
                    "type": "string"
                }
            }
        },
        "taxclient.Bracket": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                },
                "rate": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
