definitions:
  main.taxServerError:
    properties:
      error:
        type: string
    type: object
  main.taxServerResponse:
    properties:
      message:
        type: string
    type: object
  taxcalculator.BracketTax:
    properties:
      band:
        $ref: '#/definitions/taxclient.Bracket'
      tax:
        example: 984.62
        type: number
    type: object
  taxcalculator.TaxCalculation:
    properties:
      effective_rate:
        example: 0.15
        type: number
      salary:
        example: 55000
        type: number
      taxes_by_band:
        items:
          $ref: '#/definitions/taxcalculator.BracketTax'
        type: array
      total_taxes:
        example: 8514.17
        type: number
    type: object
  taxclient.Bracket:
    properties:
      max:
        example: 100392
        type: number
      min:
        example: 50197
        type: number
      rate:
        example: 0.205
        type: number
    type: object
info:
  contact:
    email: ybakhan@gmail.com
    name: Yasser Khan
    url: http://github.com/ybakhan
  description: REST API for calculating taxes
  title: Tax Calculator API
  version: "1.0"
paths:
  /tax/{year}:
    get:
      description: calculate taxes for given a salary and tax year
      parameters:
      - description: tax year
        in: path
        name: year
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/taxcalculator.TaxCalculation'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.taxServerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.taxServerError'
      summary: calculate taxes
      tags:
      - taxes
swagger: "2.0"
